/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import controllers.AccountControl;
import controllers.PackageControl;
import entities.MobileAccount;
import entities.Packages;
import java.io.IOException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sachintha
 */
public class Login extends javax.swing.JFrame {

    private MobileAccount tempMobileAccount;
    private String accountNumber;
    Vector<Packages> p = null;
    private static PackageControl thePackages = PackageControl.getInstance();

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();

        try {
            thePackages.deserialize();
        } catch (Exception e) {
        }

        p = thePackages.getAllPackages();

        jLabel15.setText(p.get(0).getPackageName());
        jLabel20.setText(p.get(1).getPackageName());
        jLabel23.setText(p.get(2).getPackageName());
        jLabel26.setText(p.get(3).getPackageName());

        jLabel18OffpeakAmount.setText(String.valueOf(p.get(0).getOffPeakCharge()));
        jLabel18OffpeakAmount1.setText(String.valueOf(p.get(1).getOffPeakCharge()));
        jLabel18OffpeakAmount2.setText(String.valueOf(p.get(2).getOffPeakCharge()));
        jLabel18OffpeakAmount3.setText(String.valueOf(p.get(3).getOffPeakCharge()));

        jLabel19PeakAmount.setText(String.valueOf(p.get(0).getPeakCharge()));
        jLabel19PeakAmount1.setText(String.valueOf(p.get(1).getPeakCharge()));
        jLabel19PeakAmount2.setText(String.valueOf(p.get(2).getPeakCharge()));
        jLabel19PeakAmount3.setText(String.valueOf(p.get(3).getPeakCharge()));

    }

    public void addMobileNumber(int mobileNumber, String name) throws ParseException, IOException {
        //getting the currennt date
        DateFormat formatter = new SimpleDateFormat("MM-dd-yyyy");
        String dateString = formatter.format(new Date());
        Date startDate = formatter.parse(dateString);

        try { //if there is no registered users
            AccountControl.deserialize(); //deserialize mobile accounts

            if (AccountControl.findMobileAccountByMobileNumber(mobileNumber) == null) { //if there is no Mobile account for the given mobile number

                MobileAccount acc = new MobileAccount(mobileNumber, startDate, name);//create new mobile account object
                AccountControl.createMobileAccount(acc);//add the new Mobile account to Account vector
                accountNumber = acc.getAccountNumber();//get latest account number
                System.out.println(" new global account number" + accountNumber);
                MobileUI.mobibleAccNo = accountNumber;//set mobile ui home account number
                AccountControl.serialize();//serialize the account control class

                //disableing next button in ipackage panel
                //jLabel_packageNext.setVisible(false);

                // removing pane
                main_panel.removeAll();
                main_panel.repaint();
                main_panel.revalidate();
                //adding pane
                main_panel.add(ipackage);
                main_panel.repaint();
                main_panel.revalidate();

            } else {//if the mobile number already exsits 
                JOptionPane.showMessageDialog(null, "Mobile number already exsits!", "Message", JOptionPane.INFORMATION_MESSAGE);

            }

        } catch (IOException ex) { //if there are registered users
            MobileAccount acc = new MobileAccount(mobileNumber, startDate, name);//create new mobile account object
            AccountControl.createMobileAccount(acc);//add the new Mobile account to Account vector
            accountNumber = acc.getAccountNumber();//get latest account number 
            MobileUI.mobibleAccNo = accountNumber;//set mobile ui home account number

            AccountControl.serialize();//serialize mobile accounts
            //jLabel_packageNext.setVisible(false); //disableing next button in ipackage panel

            // removing pane
            main_panel.removeAll();
            main_panel.repaint();
            main_panel.revalidate();
            //adding pane
            main_panel.add(ipackage);
            main_panel.repaint();
            main_panel.revalidate();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_mobileSignIn = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_loginMobileNumber = new javax.swing.JTextField();
        Page_Title12 = new javax.swing.JLabel();
        Page_Title18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Page_Title9 = new javax.swing.JLabel();
        Page_Title6 = new javax.swing.JLabel();
        Page_Title7 = new javax.swing.JLabel();
        Page_Title8 = new javax.swing.JLabel();
        white_transparent_panel_title4 = new javax.swing.JLabel();
        Page_Title10 = new javax.swing.JLabel();
        bacground_login = new javax.swing.JLabel();
        iregister = new javax.swing.JPanel();
        Page_Title11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Page_Title13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_mobileNumber = new javax.swing.JTextField();
        jTextField_userName = new javax.swing.JTextField();
        Page_Title14 = new javax.swing.JLabel();
        Page_Title38 = new javax.swing.JLabel();
        Page_Title15 = new javax.swing.JLabel();
        Page_Title16 = new javax.swing.JLabel();
        Page_Title17 = new javax.swing.JLabel();
        white_transparent_panel_title5 = new javax.swing.JLabel();
        Page_Title45 = new javax.swing.JLabel();
        bacground_login1 = new javax.swing.JLabel();
        ipayment_type = new javax.swing.JPanel();
        Page_Title20 = new javax.swing.JLabel();
        Page_Title22 = new javax.swing.JLabel();
        Page_Title23 = new javax.swing.JLabel();
        Page_Title24 = new javax.swing.JLabel();
        white_transparent_panel_title6 = new javax.swing.JLabel();
        Page_Title25 = new javax.swing.JLabel();
        Page_Title26 = new javax.swing.JLabel();
        Page_Title27 = new javax.swing.JLabel();
        Visa = new javax.swing.JLabel();
        Page_Title29 = new javax.swing.JLabel();
        bacground_login2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ipaid = new javax.swing.JPanel();
        Page_Title36 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Page_Title37 = new javax.swing.JLabel();
        jLabel3_mobileAccBalance = new javax.swing.JLabel();
        Page_Title40 = new javax.swing.JLabel();
        Page_Title41 = new javax.swing.JLabel();
        Page_Title42 = new javax.swing.JLabel();
        Page_Title43 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bacground_login4 = new javax.swing.JLabel();
        ipay = new javax.swing.JPanel();
        jTextField_mobileAccTopUpPin = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Page_Title19 = new javax.swing.JLabel();
        Page_Title21 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Page_Title47 = new javax.swing.JLabel();
        Page_Title28 = new javax.swing.JLabel();
        Page_Title30 = new javax.swing.JLabel();
        Page_Title31 = new javax.swing.JLabel();
        Page_Title32 = new javax.swing.JLabel();
        white_transparent_panel_title7 = new javax.swing.JLabel();
        Page_Title33 = new javax.swing.JLabel();
        Page_Title34 = new javax.swing.JLabel();
        Page_Title35 = new javax.swing.JLabel();
        jTextField_mobileAccTopUpCardNo = new javax.swing.JTextField();
        bacground_login3 = new javax.swing.JLabel();
        Page_Title46 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ipackage = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19PeakAmount = new javax.swing.JLabel();
        jLabel18OffpeakAmount = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18OffpeakAmount1 = new javax.swing.JLabel();
        jLabel19PeakAmount1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel18OffpeakAmount2 = new javax.swing.JLabel();
        jLabel19PeakAmount2 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel18OffpeakAmount3 = new javax.swing.JLabel();
        jLabel19PeakAmount3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Page_Title39 = new javax.swing.JLabel();
        jLabel_paystationNightPack4 = new javax.swing.JLabel();
        jLabel_paystationNightPack3 = new javax.swing.JLabel();
        jLabel_paystationNightPack2 = new javax.swing.JLabel();
        jLabel_paystationNightPack1 = new javax.swing.JLabel();
        Page_Title44 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bacground_login5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(450, 100));
        setMinimumSize(new java.awt.Dimension(325, 520));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        main_panel.setLayout(new java.awt.CardLayout());

        jPanel3.setLayout(null);

        jLabel_mobileSignIn.setBackground(new java.awt.Color(102, 102, 102));
        jLabel_mobileSignIn.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        jLabel_mobileSignIn.setForeground(java.awt.Color.white);
        jLabel_mobileSignIn.setText("                  sign in");
        jLabel_mobileSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_mobileSignInMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_mobileSignInMouseEntered(evt);
            }
        });
        jPanel3.add(jLabel_mobileSignIn);
        jLabel_mobileSignIn.setBounds(150, 330, 190, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/Icon-bueSmall.png"))); // NOI18N
        jPanel3.add(jLabel9);
        jLabel9.setBounds(160, 330, 40, 40);

        jTextField_loginMobileNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_loginMobileNumberActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField_loginMobileNumber);
        jTextField_loginMobileNumber.setBounds(160, 270, 170, 27);

        Page_Title12.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title12.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        Page_Title12.setForeground(java.awt.Color.white);
        Page_Title12.setText("beta 2");
        jPanel3.add(Page_Title12);
        Page_Title12.setBounds(250, 50, 260, 21);

        Page_Title18.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title18.setFont(new java.awt.Font("Ubuntu Light", 0, 36)); // NOI18N
        Page_Title18.setForeground(java.awt.Color.white);
        Page_Title18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Page_Title18MouseClicked(evt);
            }
        });
        jPanel3.add(Page_Title18);
        Page_Title18.setBounds(100, 20, 50, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel1.setText("Add");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel1);
        jLabel1.setBounds(150, 330, 190, 40);

        Page_Title9.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title9.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        Page_Title9.setForeground(java.awt.Color.white);
        Page_Title9.setText("Login");
        jPanel3.add(Page_Title9);
        Page_Title9.setBounds(210, 160, 70, 30);

        Page_Title6.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title6.setFont(new java.awt.Font("Ubuntu Light", 0, 36)); // NOI18N
        Page_Title6.setForeground(java.awt.Color.white);
        Page_Title6.setText("Lydia");
        jPanel3.add(Page_Title6);
        Page_Title6.setBounds(190, 10, 260, 60);

        Page_Title7.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title7.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title7.setForeground(java.awt.Color.white);
        Page_Title7.setText("Welcome to Lydia Travel Services");
        jPanel3.add(Page_Title7);
        Page_Title7.setBounds(110, 90, 280, 21);

        Page_Title8.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title8.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title8.setForeground(java.awt.Color.white);
        Page_Title8.setText("Mobile No");
        jPanel3.add(Page_Title8);
        Page_Title8.setBounds(200, 230, 90, 21);

        white_transparent_panel_title4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/back02.png"))); // NOI18N
        white_transparent_panel_title4.setText("larasparet");
        white_transparent_panel_title4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                white_transparent_panel_title4MouseClicked(evt);
            }
        });
        jPanel3.add(white_transparent_panel_title4);
        white_transparent_panel_title4.setBounds(300, 340, 50, 40);

        Page_Title10.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title10.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title10.setForeground(java.awt.Color.white);
        Page_Title10.setText("new user? sing up here");
        Page_Title10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Page_Title10MouseClicked(evt);
            }
        });
        jPanel3.add(Page_Title10);
        Page_Title10.setBounds(160, 480, 190, 20);

        bacground_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/2013-06-13-13.13.33.png"))); // NOI18N
        jPanel3.add(bacground_login);
        bacground_login.setBounds(-140, -540, 560, 1130);

        main_panel.add(jPanel3, "card2");

        iregister.setLayout(null);

        Page_Title11.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title11.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title11.setForeground(java.awt.Color.white);
        Page_Title11.setText("                  register");
        Page_Title11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Page_Title11MouseClicked(evt);
            }
        });
        iregister.add(Page_Title11);
        Page_Title11.setBounds(130, 390, 210, 40);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/Icon-bueSmall.png"))); // NOI18N
        iregister.add(jLabel14);
        jLabel14.setBounds(140, 390, 29, 40);

        Page_Title13.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title13.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        Page_Title13.setForeground(java.awt.Color.white);
        Page_Title13.setText("beta 2");
        iregister.add(Page_Title13);
        Page_Title13.setBounds(250, 50, 140, 21);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel2.setText("Add");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        iregister.add(jLabel2);
        jLabel2.setBounds(130, 390, 210, 40);
        iregister.add(jTextField_mobileNumber);
        jTextField_mobileNumber.setBounds(140, 250, 190, 27);
        iregister.add(jTextField_userName);
        jTextField_userName.setBounds(140, 320, 190, 27);

        Page_Title14.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title14.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        Page_Title14.setForeground(java.awt.Color.white);
        Page_Title14.setText("Registration");
        iregister.add(Page_Title14);
        Page_Title14.setBounds(170, 150, 170, 30);

        Page_Title38.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title38.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title38.setForeground(java.awt.Color.white);
        Page_Title38.setText("User Name");
        iregister.add(Page_Title38);
        Page_Title38.setBounds(190, 290, 90, 21);

        Page_Title15.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title15.setFont(new java.awt.Font("Ubuntu Light", 0, 36)); // NOI18N
        Page_Title15.setForeground(java.awt.Color.white);
        Page_Title15.setText("Lydia");
        iregister.add(Page_Title15);
        Page_Title15.setBounds(190, 10, 260, 60);

        Page_Title16.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title16.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title16.setForeground(java.awt.Color.white);
        Page_Title16.setText("Welcome to Lydia Travel Services");
        iregister.add(Page_Title16);
        Page_Title16.setBounds(110, 90, 280, 21);

        Page_Title17.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title17.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title17.setForeground(java.awt.Color.white);
        Page_Title17.setText("Mobile No");
        iregister.add(Page_Title17);
        Page_Title17.setBounds(190, 220, 90, 21);

        white_transparent_panel_title5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/back02.png"))); // NOI18N
        white_transparent_panel_title5.setText("larasparet");
        white_transparent_panel_title5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                white_transparent_panel_title5MouseClicked(evt);
            }
        });
        iregister.add(white_transparent_panel_title5);
        white_transparent_panel_title5.setBounds(300, 340, 50, 40);

        Page_Title45.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title45.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title45.setForeground(java.awt.Color.white);
        Page_Title45.setText("already have a account? sing in here");
        Page_Title45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Page_Title45MouseClicked(evt);
            }
        });
        iregister.add(Page_Title45);
        Page_Title45.setBounds(100, 470, 280, 20);

        bacground_login1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/2013-06-13-13.13.33.png"))); // NOI18N
        iregister.add(bacground_login1);
        bacground_login1.setBounds(-140, -540, 870, 1130);

        main_panel.add(iregister, "card2");

        ipayment_type.setLayout(null);

        Page_Title20.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title20.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        Page_Title20.setForeground(java.awt.Color.white);
        Page_Title20.setText("beta 2");
        ipayment_type.add(Page_Title20);
        Page_Title20.setBounds(250, 50, 260, 21);

        Page_Title22.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title22.setFont(new java.awt.Font("Ubuntu Light", 0, 36)); // NOI18N
        Page_Title22.setForeground(java.awt.Color.white);
        Page_Title22.setText("Lydia");
        ipayment_type.add(Page_Title22);
        Page_Title22.setBounds(190, 10, 260, 60);

        Page_Title23.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title23.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title23.setForeground(java.awt.Color.white);
        Page_Title23.setText("choose your payment type,");
        ipayment_type.add(Page_Title23);
        Page_Title23.setBounds(140, 190, 260, 20);

        Page_Title24.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title24.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title24.setForeground(java.awt.Color.white);
        Page_Title24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/phdpi.png"))); // NOI18N
        Page_Title24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Page_Title24MouseClicked(evt);
            }
        });
        ipayment_type.add(Page_Title24);
        Page_Title24.setBounds(210, 350, 90, 50);

        white_transparent_panel_title6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/back02.png"))); // NOI18N
        white_transparent_panel_title6.setText("larasparet");
        white_transparent_panel_title6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                white_transparent_panel_title6MouseClicked(evt);
            }
        });
        ipayment_type.add(white_transparent_panel_title6);
        white_transparent_panel_title6.setBounds(300, 340, 50, 40);

        Page_Title25.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title25.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title25.setForeground(java.awt.Color.white);
        Page_Title25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/mhdpi.png"))); // NOI18N
        ipayment_type.add(Page_Title25);
        Page_Title25.setBounds(210, 230, 110, 60);

        Page_Title26.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title26.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title26.setForeground(java.awt.Color.white);
        Page_Title26.setText("as your transport ");
        ipayment_type.add(Page_Title26);
        Page_Title26.setBounds(140, 130, 150, 21);

        Page_Title27.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title27.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title27.setForeground(java.awt.Color.white);
        Page_Title27.setText("partner");
        ipayment_type.add(Page_Title27);
        Page_Title27.setBounds(280, 130, 70, 21);

        Visa.setBackground(new java.awt.Color(102, 102, 102));
        Visa.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Visa.setForeground(java.awt.Color.white);
        Visa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/hdpi.png"))); // NOI18N
        Visa.setText("                ");
        Visa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VisaMouseClicked(evt);
            }
        });
        ipayment_type.add(Visa);
        Visa.setBounds(210, 290, 70, 50);

        Page_Title29.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title29.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title29.setForeground(java.awt.Color.white);
        Page_Title29.setText("Thank You for choosing Lydia ");
        ipayment_type.add(Page_Title29);
        Page_Title29.setBounds(120, 100, 240, 21);

        bacground_login2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/2013-06-13-13.13.33.png"))); // NOI18N
        ipayment_type.add(bacground_login2);
        bacground_login2.setBounds(-140, -540, 870, 1130);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/Icon-bueSmall.png"))); // NOI18N
        ipayment_type.add(jLabel12);
        jLabel12.setBounds(160, 330, 40, 40);

        main_panel.add(ipayment_type, "card2");

        ipaid.setLayout(null);

        Page_Title36.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title36.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        Page_Title36.setForeground(java.awt.Color.white);
        Page_Title36.setText("beta 2");
        ipaid.add(Page_Title36);
        Page_Title36.setBounds(250, 50, 260, 21);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/Icon-SHomrmall.png"))); // NOI18N
        ipaid.add(jLabel11);
        jLabel11.setBounds(140, 320, 29, 40);

        Page_Title37.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title37.setFont(new java.awt.Font("Ubuntu Light", 0, 36)); // NOI18N
        Page_Title37.setForeground(java.awt.Color.white);
        Page_Title37.setText("Lydia");
        ipaid.add(Page_Title37);
        Page_Title37.setBounds(190, 10, 260, 60);

        jLabel3_mobileAccBalance.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3_mobileAccBalance.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        jLabel3_mobileAccBalance.setForeground(java.awt.Color.white);
        jLabel3_mobileAccBalance.setText("$100");
        ipaid.add(jLabel3_mobileAccBalance);
        jLabel3_mobileAccBalance.setBounds(210, 250, 170, 20);

        Page_Title40.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title40.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        Page_Title40.setForeground(java.awt.Color.white);
        Page_Title40.setText("Thank You");
        ipaid.add(Page_Title40);
        Page_Title40.setBounds(180, 110, 130, 20);

        Page_Title41.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title41.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title41.setForeground(java.awt.Color.white);
        Page_Title41.setText("     Account Balanace");
        ipaid.add(Page_Title41);
        Page_Title41.setBounds(150, 190, 170, 21);

        Page_Title42.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title42.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title42.setForeground(java.awt.Color.white);
        Page_Title42.setText("                      Home");
        Page_Title42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Page_Title42MouseClicked(evt);
            }
        });
        ipaid.add(Page_Title42);
        Page_Title42.setBounds(130, 320, 230, 40);

        Page_Title43.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title43.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title43.setForeground(java.awt.Color.white);
        Page_Title43.setText("Your payment recived");
        ipaid.add(Page_Title43);
        Page_Title43.setBounds(150, 160, 180, 21);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel4.setText("Add");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        ipaid.add(jLabel4);
        jLabel4.setBounds(130, 320, 230, 40);

        bacground_login4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/2013-06-13-13.13.33.png"))); // NOI18N
        ipaid.add(bacground_login4);
        bacground_login4.setBounds(-140, -540, 870, 1130);

        main_panel.add(ipaid, "card2");

        ipay.setLayout(null);
        ipay.add(jTextField_mobileAccTopUpPin);
        jTextField_mobileAccTopUpPin.setBounds(160, 340, 160, 27);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/Icon-TOPall.png"))); // NOI18N
        ipay.add(jLabel13);
        jLabel13.setBounds(160, 400, 30, 40);

        Page_Title19.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title19.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title19.setForeground(java.awt.Color.white);
        Page_Title19.setText("pay");
        Page_Title19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Page_Title19MouseClicked(evt);
            }
        });
        ipay.add(Page_Title19);
        Page_Title19.setBounds(230, 400, 40, 40);

        Page_Title21.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title21.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        Page_Title21.setForeground(java.awt.Color.white);
        Page_Title21.setText("beta 2");
        ipay.add(Page_Title21);
        Page_Title21.setBounds(250, 50, 260, 21);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel3.setText("Add");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        ipay.add(jLabel3);
        jLabel3.setBounds(150, 400, 180, 40);

        Page_Title47.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title47.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        Page_Title47.setForeground(java.awt.Color.white);
        Page_Title47.setText("back");
        ipay.add(Page_Title47);
        Page_Title47.setBounds(110, 500, 110, 17);

        Page_Title28.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title28.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        Page_Title28.setForeground(java.awt.Color.white);
        Page_Title28.setText("100");
        ipay.add(Page_Title28);
        Page_Title28.setBounds(210, 180, 70, 30);

        Page_Title30.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title30.setFont(new java.awt.Font("Ubuntu Light", 0, 36)); // NOI18N
        Page_Title30.setForeground(java.awt.Color.white);
        Page_Title30.setText("Lydia");
        ipay.add(Page_Title30);
        Page_Title30.setBounds(190, 10, 260, 60);

        Page_Title31.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title31.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title31.setForeground(java.awt.Color.white);
        Page_Title31.setText("Your Details Safe with Us");
        ipay.add(Page_Title31);
        Page_Title31.setBounds(140, 90, 280, 21);

        Page_Title32.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title32.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title32.setForeground(java.awt.Color.white);
        Page_Title32.setText("         PIN");
        ipay.add(Page_Title32);
        Page_Title32.setBounds(180, 310, 110, 21);

        white_transparent_panel_title7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/back02.png"))); // NOI18N
        white_transparent_panel_title7.setText("larasparet");
        white_transparent_panel_title7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                white_transparent_panel_title7MouseClicked(evt);
            }
        });
        ipay.add(white_transparent_panel_title7);
        white_transparent_panel_title7.setBounds(300, 340, 50, 40);

        Page_Title33.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title33.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title33.setForeground(java.awt.Color.white);
        Page_Title33.setText("pay later? click here");
        Page_Title33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Page_Title33MouseClicked(evt);
            }
        });
        ipay.add(Page_Title33);
        Page_Title33.setBounds(160, 470, 190, 20);

        Page_Title34.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title34.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title34.setForeground(java.awt.Color.white);
        Page_Title34.setText("Total Amount");
        ipay.add(Page_Title34);
        Page_Title34.setBounds(180, 140, 130, 21);

        Page_Title35.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title35.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title35.setForeground(java.awt.Color.white);
        Page_Title35.setText("Enter your Card No");
        ipay.add(Page_Title35);
        Page_Title35.setBounds(160, 250, 200, 20);

        jTextField_mobileAccTopUpCardNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_mobileAccTopUpCardNoActionPerformed(evt);
            }
        });
        ipay.add(jTextField_mobileAccTopUpCardNo);
        jTextField_mobileAccTopUpCardNo.setBounds(160, 280, 160, 27);

        bacground_login3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/2013-06-13-13.13.33.png"))); // NOI18N
        ipay.add(bacground_login3);
        bacground_login3.setBounds(-140, -540, 870, 1130);

        Page_Title46.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title46.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title46.setForeground(java.awt.Color.white);
        Page_Title46.setText("         PIN");
        ipay.add(Page_Title46);
        Page_Title46.setBounds(190, 270, 110, 21);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel7.setText("Add");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        ipay.add(jLabel7);
        jLabel7.setBounds(130, 340, 230, 90);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel6.setText("Add");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        ipay.add(jLabel6);
        jLabel6.setBounds(280, 390, 80, 30);

        main_panel.add(ipay, "card2");

        ipackage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel15.setForeground(java.awt.Color.white);
        jLabel15.setText("ABC");
        ipackage.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 50, 30));

        jLabel19PeakAmount.setForeground(java.awt.Color.white);
        jLabel19PeakAmount.setText("0");
        ipackage.add(jLabel19PeakAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 40, 20));

        jLabel18OffpeakAmount.setForeground(java.awt.Color.white);
        jLabel18OffpeakAmount.setText("0");
        ipackage.add(jLabel18OffpeakAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 40, 20));

        jLabel18.setForeground(java.awt.Color.white);
        jLabel18.setText("Peak");
        ipackage.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 60, 20));

        jLabel19.setForeground(java.awt.Color.white);
        jLabel19.setText("Off Peak");
        ipackage.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 60, 20));

        jLabel20.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel20.setForeground(java.awt.Color.white);
        jLabel20.setText("ABC");
        ipackage.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 50, 30));

        jLabel18OffpeakAmount1.setForeground(java.awt.Color.white);
        jLabel18OffpeakAmount1.setText("0");
        ipackage.add(jLabel18OffpeakAmount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 40, 20));

        jLabel19PeakAmount1.setForeground(java.awt.Color.white);
        jLabel19PeakAmount1.setText("0");
        ipackage.add(jLabel19PeakAmount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 40, 20));

        jLabel21.setForeground(java.awt.Color.white);
        jLabel21.setText("Peak");
        ipackage.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 60, 20));

        jLabel22.setForeground(java.awt.Color.white);
        jLabel22.setText("Off Peak");
        ipackage.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 60, 20));

        jLabel23.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel23.setForeground(java.awt.Color.white);
        jLabel23.setText("ABC");
        ipackage.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 40, 30));

        jLabel18OffpeakAmount2.setForeground(java.awt.Color.white);
        jLabel18OffpeakAmount2.setText("0");
        ipackage.add(jLabel18OffpeakAmount2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 40, 20));

        jLabel19PeakAmount2.setForeground(java.awt.Color.white);
        jLabel19PeakAmount2.setText("0");
        ipackage.add(jLabel19PeakAmount2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 40, 20));

        jLabel24.setForeground(java.awt.Color.white);
        jLabel24.setText("Peak");
        ipackage.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 60, 20));

        jLabel25.setForeground(java.awt.Color.white);
        jLabel25.setText("Offpeak");
        ipackage.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 60, 20));

        jLabel26.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel26.setForeground(java.awt.Color.white);
        jLabel26.setText("ABC");
        ipackage.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 50, 30));

        jLabel18OffpeakAmount3.setForeground(java.awt.Color.white);
        jLabel18OffpeakAmount3.setText("0");
        ipackage.add(jLabel18OffpeakAmount3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 40, 20));

        jLabel19PeakAmount3.setForeground(java.awt.Color.white);
        jLabel19PeakAmount3.setText("0");
        ipackage.add(jLabel19PeakAmount3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 40, 20));

        jLabel17.setForeground(java.awt.Color.white);
        jLabel17.setText("Peak");
        ipackage.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 60, 20));

        jLabel16.setForeground(java.awt.Color.white);
        jLabel16.setText("Off Peak");
        ipackage.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 60, 20));

        Page_Title39.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title39.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        Page_Title39.setForeground(java.awt.Color.white);
        Page_Title39.setText("beta 2");
        ipackage.add(Page_Title39, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        jLabel_paystationNightPack4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel_paystationNightPack4.setText("Add");
        jLabel_paystationNightPack4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_paystationNightPack4MouseClicked(evt);
            }
        });
        ipackage.add(jLabel_paystationNightPack4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 290, 70));

        jLabel_paystationNightPack3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel_paystationNightPack3.setText("Add");
        jLabel_paystationNightPack3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_paystationNightPack3MouseClicked(evt);
            }
        });
        ipackage.add(jLabel_paystationNightPack3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 290, 70));

        jLabel_paystationNightPack2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel_paystationNightPack2.setText("Add");
        jLabel_paystationNightPack2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_paystationNightPack2MouseClicked(evt);
            }
        });
        ipackage.add(jLabel_paystationNightPack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 290, 70));

        jLabel_paystationNightPack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel_paystationNightPack1.setText("Add");
        jLabel_paystationNightPack1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_paystationNightPack1MouseClicked(evt);
            }
        });
        ipackage.add(jLabel_paystationNightPack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 290, 70));

        Page_Title44.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title44.setFont(new java.awt.Font("Ubuntu Light", 0, 36)); // NOI18N
        Page_Title44.setForeground(java.awt.Color.white);
        Page_Title44.setText("Lydia");
        ipackage.add(Page_Title44, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, -1));

        jLabel8.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("choose a package");
        ipackage.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 180, -1));

        bacground_login5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/2013-06-13-13.13.33.png"))); // NOI18N
        ipackage.add(bacground_login5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, -410, 700, -1));

        main_panel.add(ipackage, "card7");

        getContentPane().add(main_panel);
        main_panel.setBounds(-80, 0, 420, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.setVisible(false);
        new MobileUI().setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void white_transparent_panel_title4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_white_transparent_panel_title4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_white_transparent_panel_title4MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        //add a new account

    }//GEN-LAST:event_jLabel2MouseClicked

    private void white_transparent_panel_title5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_white_transparent_panel_title5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_white_transparent_panel_title5MouseClicked

    private void Page_Title10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Page_Title10MouseClicked
        // removing pane
        main_panel.removeAll();
        main_panel.repaint();
        main_panel.revalidate();
        //adding pane
        main_panel.add(iregister);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_Page_Title10MouseClicked

    private void white_transparent_panel_title6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_white_transparent_panel_title6MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_white_transparent_panel_title6MouseClicked

    private void Page_Title11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Page_Title11MouseClicked

        if (!jTextField_mobileNumber.getText().isEmpty()) {//checks if the text field is empty

            try {
                addMobileNumber(Integer.parseInt(jTextField_mobileNumber.getText()), jTextField_userName.getText()); //add a new mobile account

            } catch (ParseException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NumberFormatException e) {//handling number format exception
                JOptionPane.showMessageDialog(null, "please enter a valid mobile number", "Message", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else { //mobile number field empty
            JOptionPane.showMessageDialog(null, "please enter the mobile number", "Message", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_Page_Title11MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        main_panel.removeAll();
        main_panel.repaint();
        main_panel.revalidate();
        //adding pane
        main_panel.add(ipaid);
        main_panel.repaint();
        main_panel.revalidate();


    }//GEN-LAST:event_jLabel3MouseClicked

    private void white_transparent_panel_title7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_white_transparent_panel_title7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_white_transparent_panel_title7MouseClicked

    private void Page_Title33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Page_Title33MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Page_Title33MouseClicked

    private void jTextField_mobileAccTopUpCardNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_mobileAccTopUpCardNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_mobileAccTopUpCardNoActionPerformed

    private void Page_Title24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Page_Title24MouseClicked
        // removing pane
        main_panel.removeAll();
        main_panel.repaint();
        main_panel.revalidate();
        //adding pane
        main_panel.add(ipay);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_Page_Title24MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.setVisible(false);
        new MobileUI().setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void Page_Title19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Page_Title19MouseClicked
        //All top up fieds should be filled
        if ((!jTextField_mobileAccTopUpCardNo.getText().isEmpty()) && (!jTextField_mobileAccTopUpPin.getText().isEmpty())) {

            try {

                Double amount = thePackages.findPackageByPackageID(tempMobileAccount.getPackageType()).getAmountNeeded();
                MobileUI.topUpAccount(amount); //calling the topup method from MobileUI
                jLabel3_mobileAccBalance.setText(String.valueOf(tempMobileAccount.getAmount()));//setting mobile balance
                // removing pane
                main_panel.removeAll();
                main_panel.repaint();
                main_panel.revalidate();
                // adding pane
                main_panel.add(ipaid);
                main_panel.repaint();
                main_panel.revalidate();

                

            } catch (NumberFormatException e) { //top up amonut should be a number
                JOptionPane.showMessageDialog(null, "please enter a valid amount", "Message", JOptionPane.INFORMATION_MESSAGE);

            }
        } else {//one or more fleds are empty
            JOptionPane.showMessageDialog(null, "Please Fill All fields", "Message", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_Page_Title19MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void Page_Title42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Page_Title42MouseClicked
        this.setVisible(false);
        new MobileUI().setVisible(true);
    }//GEN-LAST:event_Page_Title42MouseClicked

    private void VisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisaMouseClicked
        // TODO add your handling code here:

        // removing pane
        main_panel.removeAll();
        main_panel.repaint();
        main_panel.revalidate();
        //adding pane
        main_panel.add(ipay);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_VisaMouseClicked

    private void jLabel_mobileSignInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_mobileSignInMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_mobileSignInMouseEntered

    private void jLabel_mobileSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_mobileSignInMouseClicked

        try {
            AccountControl.deserialize();//serializing accounts
            tempMobileAccount = AccountControl.findMobileAccountByMobileNumber(Integer.parseInt(jTextField_loginMobileNumber.getText())); //find mobile account by mobile number
            if (tempMobileAccount != null) { //found the account

                MobileUI.mobibleAccNo = tempMobileAccount.getAccountNumber();//assign account number to mobileAccNo variable in mobile ui
                this.setVisible(false);//close this ui
                new MobileUI().setVisible(true); //open mobile ui

            } else { //if mobile number doesn't exists 

                JOptionPane.showMessageDialog(null, "Incorrect Mobile number", "Message", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (NumberFormatException e) { //invalid mobile number format
            JOptionPane.showMessageDialog(null, "Invalid Mobile number", "Message", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) { //if no mobile users registered
            JOptionPane.showMessageDialog(null, "No registered users", "Message", JOptionPane.INFORMATION_MESSAGE);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jLabel_mobileSignInMouseClicked

    private void Page_Title18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Page_Title18MouseClicked
        try {

            // TODO add your handling code here:
            Thread.sleep(200);
        } catch (InterruptedException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

        System.exit(0);
    }//GEN-LAST:event_Page_Title18MouseClicked

    private void Page_Title45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Page_Title45MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Page_Title45MouseClicked

    private void jTextField_loginMobileNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_loginMobileNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_loginMobileNumberActionPerformed

    private void jLabel_paystationNightPack1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_paystationNightPack1MouseClicked

        tempMobileAccount = AccountControl.getInstance().findMobileAccountByAccountNumber(accountNumber); //setting the current user object
        tempMobileAccount.setPackageType((p.get(0).getPackageId())); //set the selected package to the user
        
        Page_Title28.setText(String.valueOf(p.get(0).getAmountNeeded()));
        // removing pane
        main_panel.removeAll();
        main_panel.repaint();
        main_panel.revalidate();
        //adding pane
        main_panel.add(ipayment_type);
        main_panel.repaint();
        main_panel.revalidate();


    }//GEN-LAST:event_jLabel_paystationNightPack1MouseClicked

    private void jLabel_paystationNightPack2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_paystationNightPack2MouseClicked
        // TODO add your handling code here:
        
         tempMobileAccount = AccountControl.getInstance().findMobileAccountByAccountNumber(accountNumber); //setting the current user object
        tempMobileAccount.setPackageType((p.get(1).getPackageId())); //set the selected package to the user
        Page_Title28.setText(String.valueOf(p.get(1).getAmountNeeded()));
        // removing pane
        main_panel.removeAll();
        main_panel.repaint();
        main_panel.revalidate();
        //adding pane
        main_panel.add(ipayment_type);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_jLabel_paystationNightPack2MouseClicked

    private void jLabel_paystationNightPack3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_paystationNightPack3MouseClicked
        // TODO add your handling code here:
        
         tempMobileAccount = AccountControl.getInstance().findMobileAccountByAccountNumber(accountNumber); //setting the current user object
        tempMobileAccount.setPackageType((p.get(2).getPackageId())); //set the selected package to the user
        Page_Title28.setText(String.valueOf(p.get(2).getAmountNeeded()));
        // removing pane
        main_panel.removeAll();
        main_panel.repaint();
        main_panel.revalidate();
        //adding pane
        main_panel.add(ipayment_type);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_jLabel_paystationNightPack3MouseClicked

    private void jLabel_paystationNightPack4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_paystationNightPack4MouseClicked
        // TODO add your handling code here:
         tempMobileAccount = AccountControl.getInstance().findMobileAccountByAccountNumber(accountNumber); //setting the current user object
        tempMobileAccount.setPackageType((p.get(3).getPackageId())); //set the selected package to the user
        Page_Title28.setText(String.valueOf(p.get(3).getAmountNeeded()));
        // removing pane
        main_panel.removeAll();
        main_panel.repaint();
        main_panel.revalidate();
        //adding pane
        main_panel.add(ipayment_type);
        main_panel.repaint();
        main_panel.revalidate();
    }//GEN-LAST:event_jLabel_paystationNightPack4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Page_Title10;
    private javax.swing.JLabel Page_Title11;
    private javax.swing.JLabel Page_Title12;
    private javax.swing.JLabel Page_Title13;
    private javax.swing.JLabel Page_Title14;
    private javax.swing.JLabel Page_Title15;
    private javax.swing.JLabel Page_Title16;
    private javax.swing.JLabel Page_Title17;
    private javax.swing.JLabel Page_Title18;
    private javax.swing.JLabel Page_Title19;
    private javax.swing.JLabel Page_Title20;
    private javax.swing.JLabel Page_Title21;
    private javax.swing.JLabel Page_Title22;
    private javax.swing.JLabel Page_Title23;
    private javax.swing.JLabel Page_Title24;
    private javax.swing.JLabel Page_Title25;
    private javax.swing.JLabel Page_Title26;
    private javax.swing.JLabel Page_Title27;
    private javax.swing.JLabel Page_Title28;
    private javax.swing.JLabel Page_Title29;
    private javax.swing.JLabel Page_Title30;
    private javax.swing.JLabel Page_Title31;
    private javax.swing.JLabel Page_Title32;
    private javax.swing.JLabel Page_Title33;
    private javax.swing.JLabel Page_Title34;
    private javax.swing.JLabel Page_Title35;
    private javax.swing.JLabel Page_Title36;
    private javax.swing.JLabel Page_Title37;
    private javax.swing.JLabel Page_Title38;
    private javax.swing.JLabel Page_Title39;
    private javax.swing.JLabel Page_Title40;
    private javax.swing.JLabel Page_Title41;
    private javax.swing.JLabel Page_Title42;
    private javax.swing.JLabel Page_Title43;
    private javax.swing.JLabel Page_Title44;
    private javax.swing.JLabel Page_Title45;
    private javax.swing.JLabel Page_Title46;
    private javax.swing.JLabel Page_Title47;
    private javax.swing.JLabel Page_Title6;
    private javax.swing.JLabel Page_Title7;
    private javax.swing.JLabel Page_Title8;
    private javax.swing.JLabel Page_Title9;
    private javax.swing.JLabel Visa;
    private javax.swing.JLabel bacground_login;
    private javax.swing.JLabel bacground_login1;
    private javax.swing.JLabel bacground_login2;
    private javax.swing.JLabel bacground_login3;
    private javax.swing.JLabel bacground_login4;
    private javax.swing.JLabel bacground_login5;
    private javax.swing.JPanel ipackage;
    private javax.swing.JPanel ipaid;
    private javax.swing.JPanel ipay;
    private javax.swing.JPanel ipayment_type;
    private javax.swing.JPanel iregister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel18OffpeakAmount;
    private javax.swing.JLabel jLabel18OffpeakAmount1;
    private javax.swing.JLabel jLabel18OffpeakAmount2;
    private javax.swing.JLabel jLabel18OffpeakAmount3;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel19PeakAmount;
    private javax.swing.JLabel jLabel19PeakAmount1;
    private javax.swing.JLabel jLabel19PeakAmount2;
    private javax.swing.JLabel jLabel19PeakAmount3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3_mobileAccBalance;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_mobileSignIn;
    private javax.swing.JLabel jLabel_paystationNightPack1;
    private javax.swing.JLabel jLabel_paystationNightPack2;
    private javax.swing.JLabel jLabel_paystationNightPack3;
    private javax.swing.JLabel jLabel_paystationNightPack4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField_loginMobileNumber;
    private javax.swing.JTextField jTextField_mobileAccTopUpCardNo;
    private javax.swing.JTextField jTextField_mobileAccTopUpPin;
    private javax.swing.JTextField jTextField_mobileNumber;
    private javax.swing.JTextField jTextField_userName;
    private javax.swing.JPanel main_panel;
    private javax.swing.JLabel white_transparent_panel_title4;
    private javax.swing.JLabel white_transparent_panel_title5;
    private javax.swing.JLabel white_transparent_panel_title6;
    private javax.swing.JLabel white_transparent_panel_title7;
    // End of variables declaration//GEN-END:variables
}
