package interfaces;

import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sachintha
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
        
    }
    
    ArrayList<String> al = new ArrayList<>();
    
    
    /**
     * 
     */
    public void selectLangauge()
    {
        
    }
    
     /**
     * 
     */
    public void addMobileNumber(int mobileNumber)
    {
        
    }
    
     /**
     * 
     */
    public void selectPaymentMethod()
    {
        String s;
        
        {
            
        }
        
    }
    
     /**
     * 
     */
    public void topUpAccount()
    {
        
    }
    
     /**
     * 
     */
    public void showMap()
    {
        
    }
    
     /**
     * 
     */
    public ArrayList showRoutes()
    {
      return null;  
    }
    
    /**
     * 
     */
    public void showHistory()
    {
      
    }
    
    
    /**
     * swith between panel method.
     * @param panel
     */
   
    
    
            
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        outerPanel = new java.awt.Panel();
        Home = new java.awt.Panel();
        Page_Title11 = new javax.swing.JLabel();
        Page_Title12 = new javax.swing.JLabel();
        Page_Title13 = new javax.swing.JLabel();
        s_icon9 = new javax.swing.JLabel();
        s_icon8 = new javax.swing.JLabel();
        Page_Title14 = new javax.swing.JLabel();
        Page_Title15 = new javax.swing.JLabel();
        white_transparent_panel_title6 = new javax.swing.JLabel();
        white_transparent_panel_title5 = new javax.swing.JLabel();
        white_transparent_panel_title8 = new javax.swing.JLabel();
        Page_Title22 = new javax.swing.JLabel();
        Page_Title23 = new javax.swing.JLabel();
        Page_Title24 = new javax.swing.JLabel();
        Page_Title25 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Page_Title20 = new javax.swing.JLabel();
        Page_Title16 = new javax.swing.JLabel();
        Page_Title21 = new javax.swing.JLabel();
        Page_Title17 = new javax.swing.JLabel();
        background_img4 = new javax.swing.JLabel();
        Page_Title18 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Page_Title19 = new javax.swing.JLabel();
        white_transparent_panel_title7 = new javax.swing.JLabel();
        Account = new java.awt.Panel();
        Page_Title4 = new javax.swing.JLabel();
        jText_Account = new javax.swing.JTextField();
        jText_Account1 = new javax.swing.JTextField();
        jText_Account2 = new javax.swing.JTextField();
        Page_Title8 = new javax.swing.JLabel();
        Page_Title10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        s_icon7 = new javax.swing.JLabel();
        paypal = new javax.swing.JRadioButton();
        paypal1 = new javax.swing.JRadioButton();
        paypal2 = new javax.swing.JRadioButton();
        Page_Title9 = new javax.swing.JLabel();
        Page_Title7 = new javax.swing.JLabel();
        Page_Title3 = new javax.swing.JLabel();
        white_transparent_panel_title4 = new javax.swing.JLabel();
        Page_Title5 = new javax.swing.JLabel();
        background_img3 = new javax.swing.JLabel();
        Page_Title6 = new javax.swing.JLabel();
        s_icon1 = new javax.swing.JLabel();
        s_icon2 = new javax.swing.JLabel();
        main_title = new javax.swing.JLabel();
        s_icon3 = new javax.swing.JLabel();
        sideBlack1 = new javax.swing.JLabel();
        img_black2 = new javax.swing.JLabel();
        Backgroud_iamge = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(450, 100));
        setMinimumSize(new java.awt.Dimension(325, 550));
        setResizable(false);
        getContentPane().setLayout(null);

        outerPanel.setLayout(new java.awt.CardLayout());

        Home.setLayout(null);

        Page_Title11.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title11.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        Page_Title11.setForeground(java.awt.Color.white);
        Page_Title11.setText("50");
        Home.add(Page_Title11);
        Page_Title11.setBounds(200, 120, 60, 17);

        Page_Title12.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title12.setFont(new java.awt.Font("Ubuntu Light", 1, 14)); // NOI18N
        Page_Title12.setForeground(java.awt.Color.white);
        Page_Title12.setText("Account Infromation");
        Home.add(Page_Title12);
        Page_Title12.setBounds(50, 220, 160, 17);

        Page_Title13.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title13.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        Page_Title13.setForeground(java.awt.Color.white);
        Page_Title13.setText("Account Balance");
        Home.add(Page_Title13);
        Page_Title13.setBounds(50, 290, 130, 17);

        s_icon9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/Icon-Small.png"))); // NOI18N
        s_icon9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s_icon9MouseClicked(evt);
            }
        });
        Home.add(s_icon9);
        s_icon9.setBounds(10, 110, 30, 40);

        s_icon8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/Icon-Small.png"))); // NOI18N
        s_icon8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s_icon8MouseClicked(evt);
            }
        });
        Home.add(s_icon8);
        s_icon8.setBounds(20, 0, 30, 40);

        Page_Title14.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title14.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        Page_Title14.setForeground(java.awt.Color.white);
        Page_Title14.setText("Traveled Times");
        Home.add(Page_Title14);
        Page_Title14.setBounds(50, 120, 110, 17);

        Page_Title15.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title15.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        Page_Title15.setForeground(java.awt.Color.white);
        Page_Title15.setText("$100");
        Home.add(Page_Title15);
        Page_Title15.setBounds(200, 160, 110, 17);

        white_transparent_panel_title6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/back02.png"))); // NOI18N
        white_transparent_panel_title6.setText("larasparet");
        white_transparent_panel_title6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                white_transparent_panel_title6MouseClicked(evt);
            }
        });
        Home.add(white_transparent_panel_title6);
        white_transparent_panel_title6.setBounds(-260, 0, 710, 20);

        white_transparent_panel_title5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/back02.png"))); // NOI18N
        white_transparent_panel_title5.setText("larasparet");
        white_transparent_panel_title5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                white_transparent_panel_title5MouseClicked(evt);
            }
        });
        Home.add(white_transparent_panel_title5);
        white_transparent_panel_title5.setBounds(-230, 220, 540, 20);

        white_transparent_panel_title8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/back02.png"))); // NOI18N
        white_transparent_panel_title8.setText("larasparet");
        white_transparent_panel_title8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                white_transparent_panel_title8MouseClicked(evt);
            }
        });
        Home.add(white_transparent_panel_title8);
        white_transparent_panel_title8.setBounds(-230, 90, 540, 20);

        Page_Title22.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title22.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        Page_Title22.setForeground(java.awt.Color.white);
        Page_Title22.setText("0771929434");
        Page_Title22.setToolTipText("0771929434");
        Home.add(Page_Title22);
        Page_Title22.setBounds(180, 260, 130, 17);

        Page_Title23.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title23.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        Page_Title23.setForeground(java.awt.Color.white);
        Page_Title23.setText("Account Balance");
        Home.add(Page_Title23);
        Page_Title23.setBounds(50, 320, 130, 17);

        Page_Title24.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title24.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        Page_Title24.setForeground(java.awt.Color.white);
        Page_Title24.setText("Mobile No");
        Page_Title24.setToolTipText("");
        Home.add(Page_Title24);
        Page_Title24.setBounds(50, 260, 130, 17);

        Page_Title25.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title25.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        Page_Title25.setForeground(java.awt.Color.white);
        Page_Title25.setText("Account Balance");
        Home.add(Page_Title25);
        Page_Title25.setBounds(50, 350, 130, 17);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel2.setText("Add");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        Home.add(jLabel2);
        jLabel2.setBounds(10, 90, 30, 390);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel6.setText("Add");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        Home.add(jLabel6);
        jLabel6.setBounds(10, 90, 300, 390);

        Page_Title20.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title20.setFont(new java.awt.Font("Ubuntu Light", 1, 14)); // NOI18N
        Page_Title20.setForeground(java.awt.Color.white);
        Page_Title20.setText("Dashbord");
        Home.add(Page_Title20);
        Page_Title20.setBounds(50, 90, 80, 17);

        Page_Title16.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title16.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title16.setForeground(java.awt.Color.white);
        Page_Title16.setText("Home");
        Home.add(Page_Title16);
        Page_Title16.setBounds(60, 0, 140, 21);

        Page_Title21.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title21.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        Page_Title21.setForeground(java.awt.Color.white);
        Page_Title21.setText("Account Balance");
        Home.add(Page_Title21);
        Page_Title21.setBounds(50, 160, 130, 17);

        Page_Title17.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title17.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title17.setForeground(java.awt.Color.white);
        Page_Title17.setText("Hi , Username");
        Home.add(Page_Title17);
        Page_Title17.setBounds(20, 50, 220, 21);

        background_img4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/2013-06-13-13.13.33.png"))); // NOI18N
        background_img4.setText("larasparet");
        Home.add(background_img4);
        background_img4.setBounds(-320, -570, 670, 1160);

        Page_Title18.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title18.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title18.setForeground(java.awt.Color.white);
        Page_Title18.setText("Add Your Account here....");
        Home.add(Page_Title18);
        Page_Title18.setBounds(10, 50, 220, 21);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel5.setText("Add");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        Home.add(jLabel5);
        jLabel5.setBounds(10, 90, 260, 280);

        Page_Title19.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title19.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        Page_Title19.setForeground(java.awt.Color.white);
        Page_Title19.setText("Account Balance");
        Home.add(Page_Title19);
        Page_Title19.setBounds(50, 200, 110, 17);

        white_transparent_panel_title7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/back02.png"))); // NOI18N
        white_transparent_panel_title7.setText("larasparet");
        white_transparent_panel_title7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                white_transparent_panel_title7MouseClicked(evt);
            }
        });
        Home.add(white_transparent_panel_title7);
        white_transparent_panel_title7.setBounds(-230, 90, 540, 20);

        outerPanel.add(Home, "card4");

        Account.setLayout(null);

        Page_Title4.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title4.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        Page_Title4.setForeground(java.awt.Color.white);
        Page_Title4.setText("Cancel");
        Page_Title4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Page_Title4MouseClicked(evt);
            }
        });
        Account.add(Page_Title4);
        Page_Title4.setBounds(200, 350, 60, 17);

        jText_Account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_AccountActionPerformed(evt);
            }
        });
        Account.add(jText_Account);
        jText_Account.setBounds(140, 230, 140, 23);

        jText_Account1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_Account1ActionPerformed(evt);
            }
        });
        Account.add(jText_Account1);
        jText_Account1.setBounds(140, 280, 140, 23);

        jText_Account2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_Account2ActionPerformed(evt);
            }
        });
        Account.add(jText_Account2);
        jText_Account2.setBounds(140, 180, 140, 23);

        Page_Title8.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title8.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        Page_Title8.setForeground(java.awt.Color.white);
        Page_Title8.setText("Top Up");
        Account.add(Page_Title8);
        Page_Title8.setBounds(50, 350, 60, 17);

        Page_Title10.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title10.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        Page_Title10.setForeground(java.awt.Color.white);
        Page_Title10.setText("Amount");
        Account.add(Page_Title10);
        Page_Title10.setBounds(30, 280, 100, 17);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel1.setText("Add");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        Account.add(jLabel1);
        jLabel1.setBounds(30, 340, 110, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/callout-red-bg (2).png"))); // NOI18N
        jLabel3.setText("Add");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        Account.add(jLabel3);
        jLabel3.setBounds(160, 340, 120, 40);

        s_icon7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/Icon-Small.png"))); // NOI18N
        s_icon7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s_icon7MouseClicked(evt);
            }
        });
        Account.add(s_icon7);
        s_icon7.setBounds(20, 0, 30, 40);

        paypal.setText("MasterCard");
        paypal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paypalActionPerformed(evt);
            }
        });
        Account.add(paypal);
        paypal.setBounds(110, 120, 115, 28);

        paypal1.setText("Visa");
        Account.add(paypal1);
        paypal1.setBounds(230, 120, 80, 28);

        paypal2.setText("PayPal");
        Account.add(paypal2);
        paypal2.setBounds(20, 120, 80, 28);

        Page_Title9.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title9.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        Page_Title9.setForeground(java.awt.Color.white);
        Page_Title9.setText("PIN");
        Account.add(Page_Title9);
        Page_Title9.setBounds(30, 230, 110, 17);

        Page_Title7.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title7.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        Page_Title7.setForeground(java.awt.Color.white);
        Page_Title7.setText("Card No");
        Account.add(Page_Title7);
        Page_Title7.setBounds(30, 180, 110, 17);

        Page_Title3.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title3.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title3.setForeground(java.awt.Color.white);
        Page_Title3.setText("Top Up");
        Account.add(Page_Title3);
        Page_Title3.setBounds(60, 0, 140, 21);

        white_transparent_panel_title4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/back02.png"))); // NOI18N
        white_transparent_panel_title4.setText("larasparet");
        white_transparent_panel_title4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                white_transparent_panel_title4MouseClicked(evt);
            }
        });
        Account.add(white_transparent_panel_title4);
        white_transparent_panel_title4.setBounds(-260, 0, 710, 20);

        Page_Title5.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title5.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title5.setForeground(java.awt.Color.white);
        Page_Title5.setText("Top Up Your Account here");
        Account.add(Page_Title5);
        Page_Title5.setBounds(20, 50, 220, 21);

        background_img3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/2013-06-13-13.13.33.png"))); // NOI18N
        background_img3.setText("larasparet");
        Account.add(background_img3);
        background_img3.setBounds(-320, -570, 670, 1160);

        Page_Title6.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title6.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title6.setForeground(java.awt.Color.white);
        Page_Title6.setText("Add Your Account here....");
        Account.add(Page_Title6);
        Page_Title6.setBounds(10, 50, 220, 21);

        outerPanel.add(Account, "card4");

        getContentPane().add(outerPanel);
        outerPanel.setBounds(30, 30, 320, 500);

        s_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/Icon-Small_1.png"))); // NOI18N
        s_icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s_icon1MouseClicked(evt);
            }
        });
        getContentPane().add(s_icon1);
        s_icon1.setBounds(0, 140, 30, 40);

        s_icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/Icon-Small_map.png"))); // NOI18N
        s_icon2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s_icon2MouseClicked(evt);
            }
        });
        getContentPane().add(s_icon2);
        s_icon2.setBounds(0, 100, 30, 40);

        main_title.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        main_title.setForeground(java.awt.Color.white);
        main_title.setText("Lydia v 2.0");
        getContentPane().add(main_title);
        main_title.setBounds(40, 0, 150, 22);

        s_icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/Icon-Small_home.png"))); // NOI18N
        s_icon3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s_icon3MouseClicked(evt);
            }
        });
        getContentPane().add(s_icon3);
        s_icon3.setBounds(0, 60, 30, 40);

        sideBlack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/28h3fwh.png"))); // NOI18N
        sideBlack1.setText("jLabel2");
        getContentPane().add(sideBlack1);
        sideBlack1.setBounds(-100, 0, 470, 550);

        img_black2.setBackground(new java.awt.Color(255, 255, 255));
        img_black2.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        img_black2.setForeground(new java.awt.Color(255, 255, 255));
        img_black2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/ash.png"))); // NOI18N
        getContentPane().add(img_black2);
        img_black2.setBounds(-80, 0, 470, 30);

        Backgroud_iamge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/2013-06-13-13.13.33.png"))); // NOI18N
        getContentPane().add(Backgroud_iamge);
        Backgroud_iamge.setBounds(-220, -460, 670, 1020);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void s_icon3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s_icon3MouseClicked
        // removing pane
        outerPanel.removeAll();
        outerPanel.repaint();
        outerPanel.revalidate();
        //adding pane
        outerPanel.add(Home);
        outerPanel.repaint();
        outerPanel.revalidate();
        
        
    }//GEN-LAST:event_s_icon3MouseClicked

    private void s_icon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s_icon1MouseClicked
            // removing pane
        outerPanel.removeAll();
        outerPanel.repaint();
        outerPanel.revalidate();
        //adding pane
        outerPanel.add(Account);
        outerPanel.repaint();
        outerPanel.revalidate();
          
    }//GEN-LAST:event_s_icon1MouseClicked

    private void s_icon2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s_icon2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_s_icon2MouseClicked

    private void white_transparent_panel_title4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_white_transparent_panel_title4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_white_transparent_panel_title4MouseClicked

    private void s_icon7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s_icon7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_s_icon7MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
              // removing pane
        outerPanel.removeAll();
        outerPanel.repaint();
        outerPanel.revalidate();
        //adding pane
        outerPanel.add(Home);
        outerPanel.repaint();
        outerPanel.revalidate();
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jText_Account2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_Account2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_Account2ActionPerformed

    private void jText_Account1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_Account1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_Account1ActionPerformed

    private void jText_AccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_AccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_AccountActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void s_icon8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s_icon8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_s_icon8MouseClicked

    private void white_transparent_panel_title5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_white_transparent_panel_title5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_white_transparent_panel_title5MouseClicked

    private void Page_Title4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Page_Title4MouseClicked
         // removing pane
        outerPanel.removeAll();
        outerPanel.repaint();
        outerPanel.revalidate();
        //adding pane
        outerPanel.add(Home);
        outerPanel.repaint();
        outerPanel.revalidate();
        
    }//GEN-LAST:event_Page_Title4MouseClicked

    private void s_icon9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s_icon9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_s_icon9MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void white_transparent_panel_title6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_white_transparent_panel_title6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_white_transparent_panel_title6MouseClicked

    private void white_transparent_panel_title7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_white_transparent_panel_title7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_white_transparent_panel_title7MouseClicked

    private void white_transparent_panel_title8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_white_transparent_panel_title8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_white_transparent_panel_title8MouseClicked

    private void paypalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paypalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paypalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel Account;
    private javax.swing.JLabel Backgroud_iamge;
    private java.awt.Panel Home;
    private javax.swing.JLabel Page_Title10;
    private javax.swing.JLabel Page_Title11;
    private javax.swing.JLabel Page_Title12;
    private javax.swing.JLabel Page_Title13;
    private javax.swing.JLabel Page_Title14;
    private javax.swing.JLabel Page_Title15;
    private javax.swing.JLabel Page_Title16;
    private javax.swing.JLabel Page_Title17;
    private javax.swing.JLabel Page_Title18;
    private javax.swing.JLabel Page_Title19;
    private javax.swing.JLabel Page_Title20;
    private javax.swing.JLabel Page_Title21;
    private javax.swing.JLabel Page_Title22;
    private javax.swing.JLabel Page_Title23;
    private javax.swing.JLabel Page_Title24;
    private javax.swing.JLabel Page_Title25;
    private javax.swing.JLabel Page_Title3;
    private javax.swing.JLabel Page_Title4;
    private javax.swing.JLabel Page_Title5;
    private javax.swing.JLabel Page_Title6;
    private javax.swing.JLabel Page_Title7;
    private javax.swing.JLabel Page_Title8;
    private javax.swing.JLabel Page_Title9;
    private javax.swing.JLabel background_img3;
    private javax.swing.JLabel background_img4;
    private javax.swing.JLabel img_black2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jText_Account;
    private javax.swing.JTextField jText_Account1;
    private javax.swing.JTextField jText_Account2;
    private javax.swing.JLabel main_title;
    private java.awt.Panel outerPanel;
    private javax.swing.JRadioButton paypal;
    private javax.swing.JRadioButton paypal1;
    private javax.swing.JRadioButton paypal2;
    private javax.swing.JLabel s_icon1;
    private javax.swing.JLabel s_icon2;
    private javax.swing.JLabel s_icon3;
    private javax.swing.JLabel s_icon7;
    private javax.swing.JLabel s_icon8;
    private javax.swing.JLabel s_icon9;
    private javax.swing.JLabel sideBlack1;
    private javax.swing.JLabel white_transparent_panel_title4;
    private javax.swing.JLabel white_transparent_panel_title5;
    private javax.swing.JLabel white_transparent_panel_title6;
    private javax.swing.JLabel white_transparent_panel_title7;
    private javax.swing.JLabel white_transparent_panel_title8;
    // End of variables declaration//GEN-END:variables
}
