/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

/**
 *
 * @author sachintha
 */
public class PayStationUi extends javax.swing.JFrame {

    /**
     * Creates new form atm
     */
    public PayStationUi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atm_outer = new javax.swing.JPanel();
        atm_home = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Page_Title30 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        Page_Title5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Page_Title7 = new javax.swing.JLabel();
        Page_Title6 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        atm_payment_selct = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Page_Title8 = new javax.swing.JLabel();
        Page_Title9 = new javax.swing.JLabel();
        Page_Title10 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        Page_Title32 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        card_selet = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Page_Title11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Page_Title12 = new javax.swing.JLabel();
        Page_Title14 = new javax.swing.JLabel();
        Page_Title13 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Page_Title31 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        card_pay = new javax.swing.JPanel();
        Page_Title15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        Page_Title16 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Page_Title19 = new javax.swing.JLabel();
        Page_Title17 = new javax.swing.JLabel();
        Page_Title33 = new javax.swing.JLabel();
        Page_Title18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        card_paid = new javax.swing.JPanel();
        Page_Title20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Page_Title22 = new javax.swing.JLabel();
        Page_Title23 = new javax.swing.JLabel();
        Page_Title24 = new javax.swing.JLabel();
        Page_Title25 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cash_pay = new javax.swing.JPanel();
        Page_Title21 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        Page_Title26 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        Page_Title27 = new javax.swing.JLabel();
        Page_Title28 = new javax.swing.JLabel();
        Page_Title29 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        select_package = new javax.swing.JPanel();
        Page_Title39 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        Page_Title34 = new javax.swing.JLabel();
        Page_Title36 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        Page_Title35 = new javax.swing.JLabel();
        Page_Title37 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        Page_Title38 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        demo = new javax.swing.JPanel();
        Page_Title43 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(629, 420));
        setResizable(false);
        getContentPane().setLayout(null);

        atm_outer.setLayout(new java.awt.CardLayout());

        atm_home.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel2.setText("Add");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        atm_home.add(jLabel2);
        jLabel2.setBounds(90, 200, 460, 30);

        Page_Title30.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title30.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        Page_Title30.setForeground(java.awt.Color.white);
        Page_Title30.setText("Select a option");
        atm_home.add(Page_Title30);
        Page_Title30.setBounds(50, 90, 170, 30);

        jLabel37.setText("Demo");
        jLabel37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel37MouseClicked(evt);
            }
        });
        atm_home.add(jLabel37);
        jLabel37.setBounds(530, 40, 40, 15);

        Page_Title5.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title5.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title5.setForeground(java.awt.Color.white);
        Page_Title5.setText("Get Tickets");
        atm_home.add(Page_Title5);
        Page_Title5.setBounds(270, 200, 170, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel3.setText("Add");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        atm_home.add(jLabel3);
        jLabel3.setBounds(90, 150, 460, 30);

        Page_Title7.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title7.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title7.setForeground(java.awt.Color.white);
        Page_Title7.setText("Get Smart Card");
        atm_home.add(Page_Title7);
        Page_Title7.setBounds(250, 150, 170, 30);

        Page_Title6.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title6.setFont(new java.awt.Font("Ubuntu Light", 0, 36)); // NOI18N
        Page_Title6.setForeground(java.awt.Color.white);
        Page_Title6.setText("Lydia ATM ");
        atm_home.add(Page_Title6);
        Page_Title6.setBounds(20, 0, 260, 60);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel26.setText("Add");
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        atm_home.add(jLabel26);
        jLabel26.setBounds(0, 0, 630, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/2013-06-13-13.13.33.png"))); // NOI18N
        atm_home.add(jLabel1);
        jLabel1.setBounds(-10, -700, 695, 1136);

        atm_outer.add(atm_home, "card2");

        atm_payment_selct.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel4.setText("Add");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        atm_payment_selct.add(jLabel4);
        jLabel4.setBounds(90, 200, 460, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel5.setText("Add");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        atm_payment_selct.add(jLabel5);
        jLabel5.setBounds(90, 150, 460, 30);

        Page_Title8.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title8.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title8.setForeground(java.awt.Color.white);
        Page_Title8.setText("Pay by Cash");
        atm_payment_selct.add(Page_Title8);
        Page_Title8.setBounds(270, 200, 170, 30);

        Page_Title9.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title9.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title9.setForeground(java.awt.Color.white);
        Page_Title9.setText("Pay by Card");
        atm_payment_selct.add(Page_Title9);
        Page_Title9.setBounds(270, 150, 170, 30);

        Page_Title10.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title10.setFont(new java.awt.Font("Ubuntu Light", 0, 36)); // NOI18N
        Page_Title10.setForeground(java.awt.Color.white);
        Page_Title10.setText("Lydia ATM ");
        atm_payment_selct.add(Page_Title10);
        Page_Title10.setBounds(20, 0, 260, 60);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel25.setText("Add");
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        atm_payment_selct.add(jLabel25);
        jLabel25.setBounds(0, 0, 630, 60);

        Page_Title32.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title32.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        Page_Title32.setForeground(java.awt.Color.white);
        Page_Title32.setText("Select a option");
        atm_payment_selct.add(Page_Title32);
        Page_Title32.setBounds(50, 90, 170, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/2013-06-13-13.13.33.png"))); // NOI18N
        atm_payment_selct.add(jLabel6);
        jLabel6.setBounds(-10, -700, 695, 1136);

        atm_outer.add(atm_payment_selct, "card2");

        card_selet.setLayout(null);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel10.setText("Add");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        card_selet.add(jLabel10);
        jLabel10.setBounds(90, 160, 460, 30);

        Page_Title11.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title11.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title11.setForeground(java.awt.Color.white);
        Page_Title11.setText("PayPal");
        card_selet.add(Page_Title11);
        Page_Title11.setBounds(290, 160, 170, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel7.setText("Add");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        card_selet.add(jLabel7);
        jLabel7.setBounds(90, 260, 460, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel8.setText("Add");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        card_selet.add(jLabel8);
        jLabel8.setBounds(90, 210, 460, 30);

        Page_Title12.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title12.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title12.setForeground(java.awt.Color.white);
        Page_Title12.setText("Visa");
        card_selet.add(Page_Title12);
        Page_Title12.setBounds(300, 210, 170, 30);

        Page_Title14.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title14.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title14.setForeground(java.awt.Color.white);
        Page_Title14.setText("Master Card");
        card_selet.add(Page_Title14);
        Page_Title14.setBounds(270, 260, 170, 30);

        Page_Title13.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title13.setFont(new java.awt.Font("Ubuntu Light", 0, 36)); // NOI18N
        Page_Title13.setForeground(java.awt.Color.white);
        Page_Title13.setText("Lydia ATM");
        card_selet.add(Page_Title13);
        Page_Title13.setBounds(20, 0, 360, 60);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel24.setText("Add");
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        card_selet.add(jLabel24);
        jLabel24.setBounds(0, 0, 630, 60);

        Page_Title31.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title31.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        Page_Title31.setForeground(java.awt.Color.white);
        Page_Title31.setText("Select a payment method");
        card_selet.add(Page_Title31);
        Page_Title31.setBounds(50, 90, 290, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/2013-06-13-13.13.33.png"))); // NOI18N
        card_selet.add(jLabel9);
        jLabel9.setBounds(-10, -700, 695, 1136);

        atm_outer.add(card_selet, "card2");

        card_pay.setLayout(null);

        Page_Title15.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title15.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        Page_Title15.setForeground(java.awt.Color.white);
        Page_Title15.setText("Pay By Card :");
        card_pay.add(Page_Title15);
        Page_Title15.setBounds(50, 90, 200, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        card_pay.add(jTextField1);
        jTextField1.setBounds(270, 180, 200, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        card_pay.add(jTextField2);
        jTextField2.setBounds(270, 130, 200, 30);

        Page_Title16.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title16.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title16.setForeground(java.awt.Color.white);
        Page_Title16.setText("Cancel The Payment");
        Page_Title16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Page_Title16MouseClicked(evt);
            }
        });
        card_pay.add(Page_Title16);
        Page_Title16.setBounds(260, 300, 170, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/callout-red-bg (2).png"))); // NOI18N
        jLabel11.setText("Add");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        card_pay.add(jLabel11);
        jLabel11.setBounds(130, 300, 410, 30);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel23.setText("Add");
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        card_pay.add(jLabel23);
        jLabel23.setBounds(0, 0, 630, 60);
        card_pay.add(jLabel16);
        jLabel16.setBounds(280, 130, 200, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel13.setText("Add");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        card_pay.add(jLabel13);
        jLabel13.setBounds(130, 250, 410, 30);

        Page_Title19.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title19.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title19.setForeground(java.awt.Color.white);
        Page_Title19.setText("Accept The Payment");
        card_pay.add(Page_Title19);
        Page_Title19.setBounds(260, 250, 170, 30);

        Page_Title17.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title17.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        Page_Title17.setForeground(java.awt.Color.white);
        Page_Title17.setText("PIN:");
        card_pay.add(Page_Title17);
        Page_Title17.setBounds(160, 180, 70, 30);

        Page_Title33.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title33.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        Page_Title33.setForeground(java.awt.Color.white);
        Page_Title33.setText("Amount:");
        card_pay.add(Page_Title33);
        Page_Title33.setBounds(160, 130, 100, 30);

        Page_Title18.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title18.setFont(new java.awt.Font("Ubuntu Light", 0, 36)); // NOI18N
        Page_Title18.setForeground(java.awt.Color.white);
        Page_Title18.setText("Lydia ATM");
        card_pay.add(Page_Title18);
        Page_Title18.setBounds(20, 0, 360, 60);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/2013-06-13-13.13.33.png"))); // NOI18N
        card_pay.add(jLabel14);
        jLabel14.setBounds(-10, -700, 695, 1136);
        card_pay.add(jLabel17);
        jLabel17.setBounds(280, 130, 200, 30);

        atm_outer.add(card_pay, "card2");

        card_paid.setLayout(null);

        Page_Title20.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title20.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        Page_Title20.setForeground(java.awt.Color.white);
        Page_Title20.setText("Payment Recived");
        card_paid.add(Page_Title20);
        Page_Title20.setBounds(210, 140, 240, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel15.setText("Add");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        card_paid.add(jLabel15);
        jLabel15.setBounds(0, 0, 630, 60);
        card_paid.add(jLabel19);
        jLabel19.setBounds(280, 130, 200, 30);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel20.setText("Add");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        card_paid.add(jLabel20);
        jLabel20.setBounds(160, 240, 260, 60);

        Page_Title22.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title22.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title22.setForeground(java.awt.Color.white);
        Page_Title22.setText("HOME");
        card_paid.add(Page_Title22);
        Page_Title22.setBounds(260, 250, 170, 30);

        Page_Title23.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title23.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        Page_Title23.setForeground(java.awt.Color.white);
        Page_Title23.setText("Thank You");
        card_paid.add(Page_Title23);
        Page_Title23.setBounds(240, 90, 270, 30);

        Page_Title24.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title24.setFont(new java.awt.Font("Ubuntu Light", 0, 36)); // NOI18N
        Page_Title24.setForeground(java.awt.Color.white);
        Page_Title24.setText("Lydia ATM");
        card_paid.add(Page_Title24);
        Page_Title24.setBounds(20, 0, 360, 60);

        Page_Title25.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title25.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        Page_Title25.setForeground(java.awt.Color.white);
        Page_Title25.setText("Don't Forget to Collect your card");
        card_paid.add(Page_Title25);
        Page_Title25.setBounds(130, 190, 370, 30);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/2013-06-13-13.13.33.png"))); // NOI18N
        card_paid.add(jLabel21);
        jLabel21.setBounds(-10, -700, 695, 1136);
        card_paid.add(jLabel22);
        jLabel22.setBounds(280, 130, 200, 30);

        atm_outer.add(card_paid, "card2");

        cash_pay.setLayout(null);

        Page_Title21.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title21.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        Page_Title21.setForeground(java.awt.Color.white);
        Page_Title21.setText("Amount:");
        cash_pay.add(Page_Title21);
        Page_Title21.setBounds(150, 150, 100, 30);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        cash_pay.add(jTextField4);
        jTextField4.setBounds(250, 150, 210, 30);

        Page_Title26.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title26.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title26.setForeground(java.awt.Color.white);
        Page_Title26.setText("Cancel The Payment");
        Page_Title26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Page_Title26MouseClicked(evt);
            }
        });
        cash_pay.add(Page_Title26);
        Page_Title26.setBounds(220, 300, 170, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/callout-red-bg (2).png"))); // NOI18N
        jLabel12.setText("Add");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        cash_pay.add(jLabel12);
        jLabel12.setBounds(150, 290, 310, 60);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel27.setText("Add");
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        cash_pay.add(jLabel27);
        jLabel27.setBounds(0, 0, 630, 60);
        cash_pay.add(jLabel18);
        jLabel18.setBounds(280, 130, 200, 30);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel28.setText("Add");
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        cash_pay.add(jLabel28);
        jLabel28.setBounds(150, 220, 310, 60);

        Page_Title27.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title27.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title27.setForeground(java.awt.Color.white);
        Page_Title27.setText("Accept The Payment");
        cash_pay.add(Page_Title27);
        Page_Title27.setBounds(220, 230, 170, 30);

        Page_Title28.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title28.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        Page_Title28.setForeground(java.awt.Color.white);
        Page_Title28.setText("Pay By Cash");
        cash_pay.add(Page_Title28);
        Page_Title28.setBounds(40, 80, 240, 30);

        Page_Title29.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title29.setFont(new java.awt.Font("Ubuntu Light", 0, 36)); // NOI18N
        Page_Title29.setForeground(java.awt.Color.white);
        Page_Title29.setText("Lydia ATM");
        cash_pay.add(Page_Title29);
        Page_Title29.setBounds(20, 0, 360, 60);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/2013-06-13-13.13.33.png"))); // NOI18N
        cash_pay.add(jLabel29);
        jLabel29.setBounds(-10, -700, 695, 1136);
        cash_pay.add(jLabel30);
        jLabel30.setBounds(280, 130, 200, 30);

        atm_outer.add(cash_pay, "card2");

        select_package.setLayout(null);

        Page_Title39.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title39.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title39.setForeground(java.awt.Color.white);
        Page_Title39.setText("Mega package");
        select_package.add(Page_Title39);
        Page_Title39.setBounds(320, 270, 170, 30);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel31.setText("Add");
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });
        select_package.add(jLabel31);
        jLabel31.setBounds(310, 260, 210, 100);

        Page_Title34.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title34.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title34.setForeground(java.awt.Color.white);
        Page_Title34.setText("Night Package");
        select_package.add(Page_Title34);
        Page_Title34.setBounds(60, 150, 170, 30);

        Page_Title36.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title36.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title36.setForeground(java.awt.Color.white);
        Page_Title36.setText("Budject Package");
        select_package.add(Page_Title36);
        Page_Title36.setBounds(60, 270, 170, 30);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel32.setText("Add");
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel32MouseEntered(evt);
            }
        });
        select_package.add(jLabel32);
        jLabel32.setBounds(50, 260, 220, 100);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel33.setText("Add");
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });
        select_package.add(jLabel33);
        jLabel33.setBounds(50, 140, 220, 100);

        Page_Title35.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title35.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        Page_Title35.setForeground(java.awt.Color.white);
        Page_Title35.setText("Day Package");
        select_package.add(Page_Title35);
        Page_Title35.setBounds(320, 150, 170, 30);

        Page_Title37.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title37.setFont(new java.awt.Font("Ubuntu Light", 0, 36)); // NOI18N
        Page_Title37.setForeground(java.awt.Color.white);
        Page_Title37.setText("Lydia ATM");
        select_package.add(Page_Title37);
        Page_Title37.setBounds(20, 0, 360, 60);

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel34.setText("Add");
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });
        select_package.add(jLabel34);
        jLabel34.setBounds(0, 0, 630, 60);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel36.setText("Add");
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
        });
        select_package.add(jLabel36);
        jLabel36.setBounds(310, 140, 210, 100);

        Page_Title38.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title38.setFont(new java.awt.Font("Ubuntu Light", 0, 24)); // NOI18N
        Page_Title38.setForeground(java.awt.Color.white);
        Page_Title38.setText("Select a package for smart card");
        select_package.add(Page_Title38);
        Page_Title38.setBounds(50, 90, 370, 30);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/2013-06-13-13.13.33.png"))); // NOI18N
        select_package.add(jLabel35);
        jLabel35.setBounds(-10, -700, 695, 1136);

        atm_outer.add(select_package, "card2");

        demo.setLayout(null);

        Page_Title43.setBackground(new java.awt.Color(102, 102, 102));
        Page_Title43.setFont(new java.awt.Font("Ubuntu Light", 0, 36)); // NOI18N
        Page_Title43.setForeground(java.awt.Color.white);
        Page_Title43.setText("Lydia ATM");
        demo.add(Page_Title43);
        Page_Title43.setBounds(20, 0, 360, 60);

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/buttonBlue1.png"))); // NOI18N
        jLabel41.setText("Add");
        jLabel41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel41MouseClicked(evt);
            }
        });
        demo.add(jLabel41);
        jLabel41.setBounds(0, 0, 630, 60);

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/2013-06-13-13.13.33.png"))); // NOI18N
        demo.add(jLabel42);
        jLabel42.setBounds(-10, -700, 695, 1136);

        atm_outer.add(demo, "card2");

        getContentPane().add(atm_outer);
        atm_outer.setBounds(0, 0, 730, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setVisible(false);
        new MobileUI().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
      // removing pane
        atm_outer.removeAll();
        atm_outer.repaint();
        atm_outer.revalidate();
        //adding pane
        atm_outer.add(select_package);
        atm_outer.repaint();
        atm_outer.revalidate();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
          // removing pane
        atm_outer.removeAll();
        atm_outer.repaint();
        atm_outer.revalidate();
        //adding pane
        atm_outer.add(cash_pay);
        atm_outer.repaint();
        atm_outer.revalidate();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
       // removing pane
        atm_outer.removeAll();
        atm_outer.repaint();
        atm_outer.revalidate();
        //adding pane
        atm_outer.add(card_selet);
        atm_outer.repaint();
        atm_outer.revalidate();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
         // removing pane
        atm_outer.removeAll();
        atm_outer.repaint();
        atm_outer.revalidate();
        //adding pane
        atm_outer.add(card_selet);
        atm_outer.repaint();
        atm_outer.revalidate();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
         // removing pane
        atm_outer.removeAll();
        atm_outer.repaint();
        atm_outer.revalidate();
        //adding pane
        atm_outer.add(card_selet);
        atm_outer.repaint();
        atm_outer.revalidate();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // removing pane
        atm_outer.removeAll();
        atm_outer.repaint();
        atm_outer.revalidate();
        //adding pane
        atm_outer.add(card_pay);
        atm_outer.repaint();
        atm_outer.revalidate();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
         // removing pane
        atm_outer.removeAll();
        atm_outer.repaint();
        atm_outer.revalidate();
        //adding pane
        atm_outer.add(card_paid);
        atm_outer.repaint();
        atm_outer.revalidate();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        

    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
         // removing pane
        atm_outer.removeAll();
        atm_outer.repaint();
        atm_outer.revalidate();
        //adding pane
        atm_outer.add(atm_home);
        atm_outer.repaint();
        atm_outer.revalidate();
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel26MouseClicked

    private void Page_Title16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Page_Title16MouseClicked
         // removing pane
        atm_outer.removeAll();
        atm_outer.repaint();
        atm_outer.revalidate();
        //adding pane
        atm_outer.add(atm_home);
        atm_outer.repaint();
        atm_outer.revalidate();
    }//GEN-LAST:event_Page_Title16MouseClicked

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void Page_Title26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Page_Title26MouseClicked
          // removing pane
        atm_outer.removeAll();
        atm_outer.repaint();
        atm_outer.revalidate();
        //adding pane
        atm_outer.add(atm_home);
        atm_outer.repaint();
        atm_outer.revalidate();
    }//GEN-LAST:event_Page_Title26MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
           // removing pane
        atm_outer.removeAll();
        atm_outer.repaint();
        atm_outer.revalidate();
        //adding pane
        atm_outer.add(card_paid);
        atm_outer.repaint();
        atm_outer.revalidate();
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        // removing pane
        atm_outer.removeAll();
        atm_outer.repaint();
        atm_outer.revalidate();
        //adding pane
        atm_outer.add(atm_payment_selct);
        atm_outer.repaint();
        atm_outer.revalidate();
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        // removing pane
        atm_outer.removeAll();
        atm_outer.repaint();
        atm_outer.revalidate();
        //adding pane
        atm_outer.add(atm_payment_selct);
        atm_outer.repaint();
        atm_outer.revalidate();
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
       // removing pane
        atm_outer.removeAll();
        atm_outer.repaint();
        atm_outer.revalidate();
        //adding pane
        atm_outer.add(atm_payment_selct);
        atm_outer.repaint();
        atm_outer.revalidate();
    }//GEN-LAST:event_jLabel33MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel34MouseClicked

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
       // removing pane
        atm_outer.removeAll();
        atm_outer.repaint();
        atm_outer.revalidate();
        //adding pane
        atm_outer.add(atm_payment_selct);
        atm_outer.repaint();
        atm_outer.revalidate();
    }//GEN-LAST:event_jLabel36MouseClicked

    private void jLabel32MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel32MouseEntered

    private void jLabel37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseClicked
        // removing pane
        atm_outer.removeAll();
        atm_outer.repaint();
        atm_outer.revalidate();
        //adding pane
        atm_outer.add(demo);
        atm_outer.repaint();
        atm_outer.revalidate();
    }//GEN-LAST:event_jLabel37MouseClicked

    private void jLabel41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel41MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel41MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayStationUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayStationUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayStationUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayStationUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayStationUi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Page_Title10;
    private javax.swing.JLabel Page_Title11;
    private javax.swing.JLabel Page_Title12;
    private javax.swing.JLabel Page_Title13;
    private javax.swing.JLabel Page_Title14;
    private javax.swing.JLabel Page_Title15;
    private javax.swing.JLabel Page_Title16;
    private javax.swing.JLabel Page_Title17;
    private javax.swing.JLabel Page_Title18;
    private javax.swing.JLabel Page_Title19;
    private javax.swing.JLabel Page_Title20;
    private javax.swing.JLabel Page_Title21;
    private javax.swing.JLabel Page_Title22;
    private javax.swing.JLabel Page_Title23;
    private javax.swing.JLabel Page_Title24;
    private javax.swing.JLabel Page_Title25;
    private javax.swing.JLabel Page_Title26;
    private javax.swing.JLabel Page_Title27;
    private javax.swing.JLabel Page_Title28;
    private javax.swing.JLabel Page_Title29;
    private javax.swing.JLabel Page_Title30;
    private javax.swing.JLabel Page_Title31;
    private javax.swing.JLabel Page_Title32;
    private javax.swing.JLabel Page_Title33;
    private javax.swing.JLabel Page_Title34;
    private javax.swing.JLabel Page_Title35;
    private javax.swing.JLabel Page_Title36;
    private javax.swing.JLabel Page_Title37;
    private javax.swing.JLabel Page_Title38;
    private javax.swing.JLabel Page_Title39;
    private javax.swing.JLabel Page_Title43;
    private javax.swing.JLabel Page_Title5;
    private javax.swing.JLabel Page_Title6;
    private javax.swing.JLabel Page_Title7;
    private javax.swing.JLabel Page_Title8;
    private javax.swing.JLabel Page_Title9;
    private javax.swing.JPanel atm_home;
    private javax.swing.JPanel atm_outer;
    private javax.swing.JPanel atm_payment_selct;
    private javax.swing.JPanel card_paid;
    private javax.swing.JPanel card_pay;
    private javax.swing.JPanel card_selet;
    private javax.swing.JPanel cash_pay;
    private javax.swing.JPanel demo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel select_package;
    // End of variables declaration//GEN-END:variables
}
