/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import controllers.PackageControl;
import entities.Packages;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author HP
 */
public class TransportProviderUI extends javax.swing.JFrame {

    /**
     * Creates new form TransportProviderUI
     */
    
    Vector col_names, packagesForTable;
    DefaultTableModel model;
    TableRowSorter<TableModel> sort_package;

    public TransportProviderUI() throws IOException  {
        initComponents();
        
   
        try {
            //deserilaize the packages
            PackageControl.deserialize();
        } catch (IOException e) {
            PackageControl.serialize();
        } catch (ClassNotFoundException e) {
          
        }
       
        
        PackageControl packageControlInstance=PackageControl.getInstance();
        Vector<Packages> allPackages=  packageControlInstance.getAllPackages();
        packagesTableLoad(allPackages);
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_peakCharge = new javax.swing.JTextField();
        jTextField_offPeakCharge = new javax.swing.JTextField();
        jTextField_amountNeeded = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField_packageName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jTextField_searchPackage = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_packages = new javax.swing.JTable();
        jTextField_editPeakCharge = new javax.swing.JTextField();
        jTextField_editOffPeakCharge = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_editAmountNeeded = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel_packageID = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField_editPackageName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Peak Charge");

        jLabel2.setText("Off Peak Charge");

        jLabel3.setText("Amount needed");

        jTextField_peakCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_peakChargeActionPerformed(evt);
            }
        });

        jButton1.setText("Add Package");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Package Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_offPeakCharge, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_amountNeeded))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField_peakCharge, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                                .addComponent(jTextField_packageName))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField_packageName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(jTextField_peakCharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_offPeakCharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_amountNeeded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Create New Package", jPanel1);

        jTextField_searchPackage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_searchPackageKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_searchPackageKeyReleased(evt);
            }
        });

        jTable_packages.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_packages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_packagesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_packages);

        jLabel5.setText("Off Peak Charge");

        jLabel6.setText("Peak Charge");

        jLabel7.setText("Amount Needed");

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Package Name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_packageID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_editPeakCharge)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_editAmountNeeded)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextField_editOffPeakCharge)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextField_editPackageName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jTextField_searchPackage))
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField_searchPackage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel_packageID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_editPackageName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_editPeakCharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_editOffPeakCharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_editAmountNeeded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addGap(40, 40, 40))
        );

        jTabbedPane1.addTab("Customize Package", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_peakChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_peakChargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_peakChargeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          //get details from the textfields 
           if(jTextField_packageName.getText().equalsIgnoreCase("")||jTextField_peakCharge.getText().equalsIgnoreCase("") || jTextField_offPeakCharge.getText().equalsIgnoreCase("") || jTextField_amountNeeded.getText().equalsIgnoreCase("")){
                JOptionPane.showMessageDialog(rootPane, "Please fill all the necessary fields");
           }
           else{
            String packageName  = jTextField_packageName.getText();
            double peakCharge    = Double.parseDouble(jTextField_peakCharge.getText());
            double offPeakCharge = Double.parseDouble(jTextField_offPeakCharge.getText());
            double amountNeeded = Double.parseDouble(jTextField_amountNeeded.getText());
            
         //creating a new package 
            Packages pack = new Packages(packageName,peakCharge,offPeakCharge,amountNeeded);
            
             PackageControl.getInstance().createPackage(pack);
             
               try {
                   //serializing the packages
                   PackageControl.serialize();
                   JOptionPane.showMessageDialog(rootPane, "Package successfully added");
                   jTextField_packageName.setText("");
                   jTextField_peakCharge.setText("");
                   jTextField_offPeakCharge.setText("");
                   jTextField_amountNeeded.setText("");
                 
                   
               } catch (IOException e) {
                   
                   JOptionPane.showMessageDialog(rootPane, "An error ocuured while adding the package.please reenter");
               }
            }
               //loading packages
                PackageControl packageControlInstance=PackageControl.getInstance();
                Vector<Packages> allPackages=  packageControlInstance.getAllPackages();
                packagesTableLoad(allPackages);
            
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable_packagesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_packagesMouseClicked
     
        int r= jTable_packages.getSelectedRow();
          
         jLabel_packageID.setText(jTable_packages.getValueAt(r,0).toString());
         jTextField_editPackageName.setText(jTable_packages.getValueAt(r,1).toString());
         jTextField_editPeakCharge.setText(jTable_packages.getValueAt(r,2).toString());
         jTextField_editOffPeakCharge.setText(jTable_packages.getValueAt(r,3).toString());
         jTextField_editAmountNeeded.setText(jTable_packages.getValueAt(r,4).toString());
        
        
    }//GEN-LAST:event_jTable_packagesMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         String packageID =jLabel_packageID.getText();
         String packageName =  jTextField_editPackageName.getText();
         double peakCharge    = Double.parseDouble(jTextField_editPeakCharge.getText());
         double offPeakCharge = Double.parseDouble(jTextField_editOffPeakCharge.getText());
         double amountNeeded  = Double.parseDouble(jTextField_editAmountNeeded.getText());
         
         Packages pack= PackageControl.getInstance().findPackageByPackageID(packageID);
                 pack.setPackageName(packageName);
                 pack.setPeakCharge(peakCharge);
                 pack.setOffPeakCharge(offPeakCharge);
                 pack.setAmountNeeded(amountNeeded);
         
        try {
            PackageControl.serialize();
            JOptionPane.showMessageDialog(rootPane, "Package updated successfully");
                   jLabel_packageID.setText("");
                   jTextField_editPackageName.setText("");
                   jTextField_editPeakCharge.setText("");
                   jTextField_editOffPeakCharge.setText("");
                   jTextField_editAmountNeeded.setText("");
        } catch (IOException e) {
           JOptionPane.showMessageDialog(rootPane, "An error ocuured while updating the package.please reenter");
        }
         //loading packages
                PackageControl packageControlInstance=PackageControl.getInstance();
                Vector<Packages> allPackages=  packageControlInstance.getAllPackages();
                packagesTableLoad(allPackages);
                      
         
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField_searchPackageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_searchPackageKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_searchPackageKeyPressed

    private void jTextField_searchPackageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_searchPackageKeyReleased
       String packageID = jTextField_searchPackage.getText();
      if(packageID.equalsIgnoreCase("")||packageID == null){
        PackageControl packageControlInstance=PackageControl.getInstance();
        Vector<Packages> allPackages=  packageControlInstance.getAllPackages();
        packagesTableLoad(allPackages);
      }
      
      else{
      Packages pack= PackageControl.getInstance().findPackageByPackageID(packageID);
      Vector<Packages> resultedPackages= new Vector<Packages>();
      resultedPackages.add(pack);
      packagesTableLoad(resultedPackages);
      }
        
    }//GEN-LAST:event_jTextField_searchPackageKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransportProviderUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransportProviderUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransportProviderUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransportProviderUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TransportProviderUI().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(TransportProviderUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    public void packagesTableLoad(Vector<Packages> setOfPackages ){
        col_names = new Vector();
        col_names.add("Package ID");
        col_names.add("Package Name");
        col_names.add("Peak Charge");
        col_names.add("Off Peak Charge");
        col_names.add("Amount needed");
     
        packagesForTable = new Vector<Vector<String>>();
      for(Packages pack:setOfPackages)
          {
            Vector v=new Vector();
            v.add(pack.getPackageId());
            v.add(pack.getPackageName());
            v.add(pack.getPeakCharge());
            v.add(pack.getOffPeakCharge());
            v.add(pack.getAmountNeeded());
       
            
         packagesForTable.add(v);
           
          }
        model = new DefaultTableModel( packagesForTable,col_names);
        jTable_packages.setModel(model);
        sort_package= new TableRowSorter<TableModel> (model);
        jTable_packages.setRowSorter( sort_package);
        jScrollPane1.setViewportView( jTable_packages);
        jTable_packages.setAutoscrolls(true);
        jTable_packages.getTableHeader().setReorderingAllowed(false);
    
    
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_packageID;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_packages;
    private javax.swing.JTextField jTextField_amountNeeded;
    private javax.swing.JTextField jTextField_editAmountNeeded;
    private javax.swing.JTextField jTextField_editOffPeakCharge;
    private javax.swing.JTextField jTextField_editPackageName;
    private javax.swing.JTextField jTextField_editPeakCharge;
    private javax.swing.JTextField jTextField_offPeakCharge;
    private javax.swing.JTextField jTextField_packageName;
    private javax.swing.JTextField jTextField_peakCharge;
    private javax.swing.JTextField jTextField_searchPackage;
    // End of variables declaration//GEN-END:variables
}
